# Generated by Django 4.2.4 on 2023-08-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_room',
        ),
    ]
