# Generated by Django 4.2.4 on 2023-09-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_alter_owner_guest_alter_owner_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='guest',
            new_name='guest_room',
        ),
    ]
