# Generated by Django 4.2.4 on 2023-09-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_rename_guest_owner_guest_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='guest_room',
            new_name='guest',
        ),
    ]
