# Generated by Django 4.2.4 on 2023-09-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_admin_email_remove_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='resrved',
            new_name='reserved',
        ),
    ]
