# Generated by Django 4.2.4 on 2023-09-11 08:33

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_resrved_hotel_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('date_reserved', models.DateField(auto_now_add=True)),
                ('resrved', models.BooleanField(default=False)),
                ('date_unreserved', models.DateField(default=users.models.get_date_time)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='date_reserved',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='date_unreserved',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_number',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.BigIntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.room'),
            preserve_default=False,
        ),
    ]
