# Generated by Django 4.2.4 on 2023-09-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_date_reserved_room_date_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='resrved',
            new_name='reserved',
        ),
    ]
