# Generated by Django 4.2.4 on 2023-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_resrved_room_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserver_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
