# Generated by Django 4.2.4 on 2023-09-12 07:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_room_reserver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserve',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_unreserved',
            field=models.DateField(default=users.models.get_date_time, null=True),
        ),
    ]
