# Generated by Django 4.2.4 on 2023-09-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_room_date_reserve_alter_room_date_unreserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserve',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
