# Generated by Django 4.2.4 on 2023-09-12 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_room_date_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserve',
            field=models.DateField(default=datetime.date(2023, 9, 12), null=True),
        ),
    ]
