# Generated by Django 4.2.4 on 2023-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_room_date_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserver_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
