# Generated by Django 4.2.4 on 2023-09-19 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_room_date_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserve',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 11, 43, 43, 973159, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
