# Generated by Django 4.2.4 on 2023-09-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_room_date_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_reserve',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_unreserved',
        ),
        migrations.RemoveField(
            model_name='room',
            name='reserved',
        ),
    ]
