# Generated by Django 4.2.4 on 2023-09-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_room_date_reserve_remove_room_date_unreserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='until_reserve',
            field=models.DateTimeField(null=True),
        ),
    ]
