# Generated by Django 4.2.4 on 2023-08-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomchoice',
            old_name='number_room',
            new_name='room_number',
        ),
    ]
