# Generated by Django 4.2.4 on 2023-08-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_number_room_roomchoice_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='choice_room_number',
        ),
    ]
