# Generated by Django 4.2.4 on 2023-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_room_number_room_choice_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
