# Generated by Django 4.2.4 on 2023-09-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0004_room_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guests.guest'),
            preserve_default=False,
        ),
    ]
