# Generated by Django 4.2.4 on 2023-09-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='choice_room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomchoice', to_field='room_number'),
        ),
        migrations.AlterField(
            model_name='roomchoice',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
