# Generated by Django 4.2.4 on 2023-09-09 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_date_reserved_remove_room_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_reserved',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
