# Generated by Django 4.2.4 on 2023-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_date_reserved_room_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserved',
            field=models.DateField(),
        ),
    ]
