# Generated by Django 4.2.4 on 2023-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_date_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
