# Generated by Django 4.2.4 on 2023-09-10 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_room_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_reserved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
