# Generated by Django 4.2.4 on 2023-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_room_date_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchoice',
            name='room_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
