# Generated by Django 4.2.4 on 2023-09-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_guest'),
        ('rooms', '0013_remove_room_guests_room_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='guests.guest'),
            preserve_default=False,
        ),
    ]
