# Generated by Django 4.2.4 on 2023-09-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_guest'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest'),
        ),
    ]
